
export type PolicyId =
  | 'terms-of-service'
  | 'privacy-policy'
  | 'community-guidelines'
  | 'payments-virtual-currency'
  | 'fraud-chargeback'
  | 'creator-earnings-payout'
  | 'dispute-arbitration'
  | 'account-enforcement-termination'
  | 'aml-summary'
  | 'law-enforcement-cooperation'
  | 'transparency-enforcement-overview';

export type PolicyAudience = 'web' | 'mobile' | 'all';

export interface PolicySection {
  heading: string;
  content: string;
  audience?: PolicyAudience;
}

export interface Policy {
  id: PolicyId;
  title: string;
  effectiveDate: string;
  lastUpdated: string;
  summary?: string;
  sections: PolicySection[];
}

const EFFECTIVE_DATE = 'January 1, 2026';
const LAST_UPDATED = 'January 1, 2026';
const LEGAL_ENTITY = 'MyLiveLinks LLC';
const CONTACT_EMAIL = 'brad@mylivelinks.com';

const PROHIBITED_PROSTITUTION_LANGUAGE =
  "Prostitution and sexual services are not allowed. This includes offering, requesting, or arranging in-person sexual services, escorting, paid sex acts, or any content that facilitates sexual services. Any attempt to use the platform for prostitution or sexual services will result in immediate enforcement action, including suspension or permanent termination, and may be reported to law enforcement.";

export const POLICIES: Policy[] = [
  {
    id: 'terms-of-service',
    title: 'Terms of Service',
    effectiveDate: EFFECTIVE_DATE,
    lastUpdated: LAST_UPDATED,
    summary: 'Rules for using MyLiveLinks, including user responsibilities, prohibited conduct, and platform enforcement.',
    sections: [
      {
        heading: '1. Who we are',
        content: `MyLiveLinks is operated by ${LEGAL_ENTITY} ("MyLiveLinks", "we", "us").\n\nContact: ${CONTACT_EMAIL}`,
      },
      {
        heading: '2. Eligibility',
        content:
          'You must be at least 13 years old to use MyLiveLinks. Some features may be limited to users who are 18+ or who complete additional verification.',
      },
      {
        heading: '3. Your account',
        content:
          'You are responsible for maintaining the confidentiality of your account and for all activity under your account. You agree to provide accurate information and keep it up to date.',
      },
      {
        heading: '4. Prohibited conduct',
        content:
          `You may not use MyLiveLinks to break the law, harass others, exploit or endanger minors, or distribute illegal or harmful content.\n\n${PROHIBITED_PROSTITUTION_LANGUAGE}`,
      },
      {
        heading: '5. Content and community',
        content:
          'You are responsible for the content you post. Do not post content that is illegal, hateful, threatening, sexually exploitative, or that violates the rights of others. You must comply with our Community Guidelines.',
      },
      {
        heading: '6. Payments, virtual currency, and creator earnings',
        content:
          'If you purchase virtual currency or send gifts, you agree to our Payments & Virtual Currency Policy and our Fraud/Chargeback Policy. Creators who earn from gifts are subject to our Creator Earnings & Payout Policy.',
      },
      {
        heading: '7. Enforcement and termination',
        content:
          'We may suspend or terminate accounts, remove content, and restrict features to enforce these Terms and protect users. See our Account Enforcement & Termination Policy for more details.',
      },
      {
        heading: '8. Disputes and arbitration',
        content:
          'Disputes are governed by our Dispute & Arbitration Policy, which may require arbitration and may limit the ability to participate in class actions where permitted by law.',
      },
      {
        heading: '9. Changes',
        content:
          'We may update these Terms from time to time. If changes are material, we will provide notice where required. Your continued use after changes means you accept the updated Terms.',
      },
    ],
  },
  {
    id: 'privacy-policy',
    title: 'Privacy Policy',
    effectiveDate: EFFECTIVE_DATE,
    lastUpdated: LAST_UPDATED,
    summary: 'How we collect, use, and share information, and your privacy choices.',
    sections: [
      {
        heading: '1. Information we collect',
        content:
          'We collect information you provide (such as account details and profile information), information generated by your use of the service (such as posts, interactions, and device data), and information from payments or verification providers where applicable.',
      },
      {
        heading: '2. How we use information',
        content:
          'We use information to operate the service, provide features, personalize content, prevent fraud, comply with legal obligations, and enforce our policies.',
      },
      {
        heading: '3. Sharing',
        content:
          'We may share information with service providers (e.g., hosting, analytics, fraud prevention, payment processors), for legal compliance, and with other users based on your settings and the content you choose to publish.',
      },
      {
        heading: '4. Data retention',
        content:
          'We retain information as long as needed for the purposes described in this policy, including legal compliance, dispute resolution, and enforcement, unless a longer retention period is required or permitted by law.',
      },
      {
        heading: '5. Your choices',
        content:
          'You can update certain profile data, adjust visibility settings where available, and request access or deletion where required by applicable law.',
      },
      {
        heading: '6. Contact',
        content: `Questions: ${CONTACT_EMAIL}`,
      },
    ],
  },
  {
    id: 'community-guidelines',
    title: 'Community Guidelines',
    effectiveDate: EFFECTIVE_DATE,
    lastUpdated: LAST_UPDATED,
    summary: 'Standards for safe and respectful use of MyLiveLinks, including prohibited content and behaviors.',
    sections: [
      {
        heading: '1. Be respectful',
        content:
          'Harassment, hate, threats, doxxing, and targeted abuse are not allowed. Do not encourage self-harm or violence.',
      },
      {
        heading: '2. Safety and illegal activity',
        content:
          'Do not use MyLiveLinks for illegal activity, including trafficking, exploitation, or fraud. Do not share instructions for wrongdoing.',
      },
      {
        heading: '3. Sexual services and prostitution',
        content: PROHIBITED_PROSTITUTION_LANGUAGE,
      },
      {
        heading: '4. Minors and exploitation',
        content:
          'Content that sexualizes minors, exploits minors, or depicts child sexual abuse material (CSAM) is strictly prohibited and will be reported.',
      },
      {
        heading: '5. Enforcement',
        content:
          'We may remove content, restrict features, or suspend/terminate accounts for violations. We may also cooperate with law enforcement where required or appropriate.',
      },
    ],
  },
  {
    id: 'payments-virtual-currency',
    title: 'Payments & Virtual Currency Policy',
    effectiveDate: EFFECTIVE_DATE,
    lastUpdated: LAST_UPDATED,
    summary: 'How virtual currency purchases and gifting work, including refunds and restrictions.',
    sections: [
      {
        heading: '1. Virtual currency',
        content:
          'MyLiveLinks may offer virtual currency that can be purchased and used to send gifts or access certain features. Virtual currency has no cash value except where explicitly described in creator payout terms.',
      },
      {
        heading: '2. Purchases',
        content:
          'Purchases may be processed by third-party payment providers (including Stripe). You agree to provide accurate billing information and authorize charges.',
      },
      {
        heading: '3. Refunds',
        content:
          'Refunds are handled according to applicable law and payment provider rules. If a charge is reversed (refund, dispute, or chargeback), we may reverse associated virtual currency or benefits and may take enforcement action as described in related policies.',
      },
    ],
  },
  {
    id: 'fraud-chargeback',
    title: 'Fraud & Chargeback Policy',
    effectiveDate: EFFECTIVE_DATE,
    lastUpdated: LAST_UPDATED,
    summary: 'How we handle fraud, payment disputes, and chargebacks.',
    sections: [
      {
        heading: '1. Fraud prevention',
        content:
          'We monitor for suspected fraud, abuse, and unauthorized payments. We may place holds, restrict features, or require verification.',
      },
      {
        heading: '2. Disputes and chargebacks',
        content:
          'If you file a dispute or chargeback, we may restrict your account and reverse virtual currency or benefits associated with the transaction where permitted. Repeated chargebacks may result in termination.',
      },
    ],
  },
  {
    id: 'creator-earnings-payout',
    title: 'Creator Earnings & Payout Policy',
    effectiveDate: EFFECTIVE_DATE,
    lastUpdated: LAST_UPDATED,
    summary: 'How creators earn from gifts and how payouts are handled, including holds and reversals.',
    sections: [
      {
        heading: '1. Earnings and conversion',
        content:
          'Creators may earn from gifts subject to platform rules, fees, and conversion rates. Conversion rates and eligibility may change over time.',
      },
      {
        heading: '2. Holds and reversals',
        content:
          'We may place holds or reverse earnings in cases of fraud, chargebacks, disputes, policy violations, or legal requirements.',
      },
      {
        heading: '3. Payouts',
        content:
          'Payout availability may require identity verification and compliance checks. Payout timing may vary based on risk signals and provider processing.',
      },
    ],
  },
  {
    id: 'dispute-arbitration',
    title: 'Dispute & Arbitration Policy',
    effectiveDate: EFFECTIVE_DATE,
    lastUpdated: LAST_UPDATED,
    summary: 'A summary of dispute resolution and arbitration expectations.',
    sections: [
      {
        heading: '1. Informal resolution first',
        content: `Contact us at ${CONTACT_EMAIL} to attempt informal resolution before filing a formal claim.`,
      },
      {
        heading: '2. Arbitration',
        content:
          'Where permitted by law, disputes may be resolved by binding arbitration rather than court, and may limit the ability to participate in class actions. The exact process depends on jurisdiction and applicable law.',
      },
    ],
  },
  {
    id: 'account-enforcement-termination',
    title: 'Account Enforcement & Termination Policy',
    effectiveDate: EFFECTIVE_DATE,
    lastUpdated: LAST_UPDATED,
    summary: 'How we enforce rules, issue warnings, and suspend/terminate accounts.',
    sections: [
      {
        heading: '1. Enforcement actions',
        content:
          'Enforcement actions may include content removal, feature limits, warnings, temporary suspensions, and permanent termination.',
      },
      {
        heading: '2. Severe violations',
        content:
          'Severe violations (including sexual exploitation, prostitution/sexual services facilitation, fraud, or threats of violence) may result in immediate termination without prior warning.',
      },
      {
        heading: '3. Appeals',
        content:
          'Where available, you may request review by contacting support. We may require additional information to investigate.',
      },
    ],
  },
  {
    id: 'aml-summary',
    title: 'Anti-Money Laundering (AML) Summary',
    effectiveDate: EFFECTIVE_DATE,
    lastUpdated: LAST_UPDATED,
    summary: 'High-level overview of AML expectations for monetization features.',
    sections: [
      {
        heading: '1. Purpose',
        content:
          'We take reasonable measures to deter money laundering, fraud, and financial abuse. This may include monitoring and verification for certain payout or payment activities.',
      },
      {
        heading: '2. Verification',
        content:
          'We may request identity verification or additional information to comply with payment provider and legal requirements.',
      },
    ],
  },
  {
    id: 'law-enforcement-cooperation',
    title: 'Law Enforcement Cooperation',
    effectiveDate: EFFECTIVE_DATE,
    lastUpdated: LAST_UPDATED,
    summary: 'How we respond to lawful requests and report severe violations.',
    sections: [
      {
        heading: '1. Cooperation',
        content:
          'We may respond to lawful requests for information and may preserve data as required. We may report suspected illegal activity where appropriate.',
      },
      {
        heading: '2. Urgent threats',
        content:
          'If we believe there is an imminent threat to safety, we may share limited information with relevant authorities consistent with law.',
      },
    ],
  },
  {
    id: 'transparency-enforcement-overview',
    title: 'Transparency & Enforcement Overview',
    effectiveDate: EFFECTIVE_DATE,
    lastUpdated: LAST_UPDATED,
    summary: 'What we enforce and how users can report violations.',
    sections: [
      {
        heading: '1. Reporting',
        content:
          'Use in-app reporting tools where available. Provide clear details and evidence to help investigation. False or abusive reports may be actioned.',
      },
      {
        heading: '2. Transparency',
        content:
          'We may publish aggregated enforcement metrics over time. We prioritize user safety, legal compliance, and platform integrity.',
      },
      {
        heading: '3. Contact',
        content: `Policy questions: ${CONTACT_EMAIL}`,
      },
    ],
  },
];

export function getPolicyById(id: string): Policy | null {
  return POLICIES.find((p) => p.id === id) ?? null;
}

export function getPoliciesForAudience(audience: PolicyAudience): Policy[] {
  if (audience === 'all') return POLICIES;

  return POLICIES.map((policy) => {
    const sections = policy.sections.filter((s) => !s.audience || s.audience === 'all' || s.audience === audience);
    return { ...policy, sections };
  });
}

